### ISSUE TITLE
docker deploy friendly 

### ISSUE THREAD

**Issue by hooopo** [pingcap-inc/ossinsight-api#57]
1. system variables are set, but node does not read it.
https://github.com/pingcap/ossinsight/pull/438#discussion_r905313030
2. allow empty password
```
docker exec -it 937b8435ef7a sh
/usr/src/app # env
CONNECTION_LIMIT=10
NODE_VERSION=16.15.1
HOSTNAME=937b8435ef7a
DB_PORT=4000
YARN_VERSION=1.22.19
SHLVL=1
HOME=/root
GH_TOKENS='aaa'
PREFETCH_CONCURRENT=3
DB_DATABASE=gharchive_dev
TERM=xterm
QUEUE_LIMIT=20
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DB_PASSWORD=''
PWD=/usr/src/app
SERVER_PORT=3450
DB_HOST=tidb
DB_USER=root
```

**Comment by Mini256** [comment]
fixed by https://github.com/pingcap-inc/ossinsight-api/commit/7ffa74ba6cf62f46bf936b4f075c945342542538  / https://github.com/pingcap-inc/ossinsight-api/commit/16ec9d00d98ae0db57a9269b083dec0a531c17a7
